---
deployment:
  tasks:
    # Ruta de despliegue en HostGator/cPanel
    - export DEPLOYPATH=$HOME/public_html/

    # Despliegue simple: copiar artefactos ya construidos (sin build en servidor)
    - mkdir -p "$DEPLOYPATH"
    - rm -rf "$DEPLOYPATH"/*
    - cp -a dist/. "$DEPLOYPATH"/
    # Copiar .htaccess para SPA/HTTPS si existe en public/
    - cp public/.htaccess "$DEPLOYPATH"/.htaccess || true

    # Log final
    - echo "Deploy completado en $DEPLOYPATH a las $(date)"