deployment:
  tasks:
    - /bin/echo Deploy start $(date)
    - /bin/mkdir -p $HOME/public_html
    - /bin/cp -R dist/* $HOME/public_html/
    - /bin/cp -f dist/.htaccess $HOME/public_html/.htaccess || true
    - /bin/echo Deploy end $(date)