---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/audedevc/public_html/
    - mkdir -p "$DEPLOYPATH"
    - rm -rf "$DEPLOYPATH"/*
    - cp -a dist/. "$DEPLOYPATH"/
    - echo "Deploy completado en $DEPLOYPATH a las $(date)"