deployment:
  tasks:
    # Copiar build a public_html en HostGator/cPanel
    - /bin/mkdir -p "$HOME/public_html"
    - /bin/rm -rf "$HOME/public_html"/*
    - /bin/cp -a dist/. "$HOME/public_html"/
    - /bin/cp public/.htaccess "$HOME/public_html"/.htaccess || true
    - /bin/echo "Deploy completado en $HOME/public_html a las $(date)"