name: Deploy to HostGator (public_html)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'vite.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy-hostgator.yml'
      - 'dist/**'

permissions:
  contents: read

concurrency:
  group: hostgator-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: hostgator
      url: https://www.audedev.com/
    env:
      # Defaults
      FTP_SERVER_DEFAULT: ftp.audedev.com
      FTP_USERNAME_DEFAULT: sitebuilder@audedev.com
      FTP_PORT_DEFAULT: '21'
      FTP_PROTOCOL_DEFAULT: ftps
      # Secrets as env (para poder usarlos en condiciones)
      FTP_PASSWORD_SECRET: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
      FTP_SERVER_SECRET: ${{ secrets.HOSTGATOR_FTP_SERVER }}
      FTP_USERNAME_SECRET: ${{ secrets.HOSTGATOR_FTP_USERNAME }}
      FTP_PORT_SECRET: ${{ secrets.HOSTGATOR_FTP_PORT }}
      FTP_PROTOCOL_SECRET: ${{ secrets.HOSTGATOR_FTP_PROTOCOL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        env:
          VITE_BASE: '/'
        run: npm run web:build

      - name: Ensure SPA fallback (optional)
        run: cp dist/index.html dist/404.html || true

      - name: Skip deploy when password secret missing
        if: ${{ env.FTP_PASSWORD_SECRET == '' }}
        run: |
          echo "Skipping deploy: falta HOSTGATOR_FTP_PASSWORD"

      - name: Resolve FTP inputs
        if: ${{ env.FTP_PASSWORD_SECRET != '' }}
        run: |
          SERVER="${FTP_SERVER_SECRET:-${FTP_SERVER_DEFAULT}}"
          USERNAME="${FTP_USERNAME_SECRET:-${FTP_USERNAME_DEFAULT}}"
          PORT="${FTP_PORT_SECRET:-${FTP_PORT_DEFAULT}}"
          PROTOCOL="${FTP_PROTOCOL_SECRET:-${FTP_PROTOCOL_DEFAULT}}"
          echo "FTP_SERVER_RESOLVED=$SERVER" >> $GITHUB_ENV
          echo "FTP_USERNAME_RESOLVED=$USERNAME" >> $GITHUB_ENV
          echo "FTP_PORT_RESOLVED=$PORT" >> $GITHUB_ENV
          echo "FTP_PROTOCOL_RESOLVED=$PROTOCOL" >> $GITHUB_ENV
          echo "Resolved server=$SERVER user=$USERNAME port=$PORT protocol=$PROTOCOL"

      - name: Deploy to HostGator via FTPS (primario)
        id: ftps
        continue-on-error: true
        if: ${{ env.FTP_PASSWORD_SECRET != '' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ env.FTP_SERVER_RESOLVED }}
          username: ${{ env.FTP_USERNAME_RESOLVED }}
          password: ${{ env.FTP_PASSWORD_SECRET }}
          local-dir: ./dist/
          server-dir: /public_html/
          protocol: ${{ env.FTP_PROTOCOL_RESOLVED }}
          port: ${{ env.FTP_PORT_RESOLVED }}
          timeout: 600000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**

      - name: Fallback deploy via FTP (si FTPS falla)
        if: ${{ steps.ftps.outcome == 'failure' && env.FTP_PASSWORD_SECRET != '' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ env.FTP_SERVER_RESOLVED }}
          username: ${{ env.FTP_USERNAME_RESOLVED }}
          password: ${{ env.FTP_PASSWORD_SECRET }}
          local-dir: ./dist/
          server-dir: /public_html/
          protocol: ftp
          port: 21
          timeout: 600000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**